project:
  title: "Hugo Tameirão Seixas"
  output-dir: ./_site/en

website:
  search: false
  navbar:
    title: false
    pinned: true
    collapse: true
    background: dark
    left:
      - href: index.qmd
        text: Home
      - file: projects.qmd
        text: Projects
      - file: publications.qmd
        text: Publications
      - file: resources.qmd
        text: Resources
      - file: services.qmd
        text: Services
    right:
      - href: ../en
        text: EN
      - href: ../pt
        text: PT

lang: en

format:
  html:
    theme: 
      - lux
      - styles.scss
    mainfont: Maven Pro
