---
title: "Resources"
filters: [remove_title.lua]
---

::: {.content-visible when-profile="en"}

This is a list of resources that I am always looking for information, I consider them as essential material for my professional work as a researcher and a data analyst. If you can't have access to any of these, please, reach me by email so that I can try to help you.

# Statistics

#### Statistical Rethinking (2019)

This book is written by Richard McElreath, it talks about a different way of looking at statistics and inferences.
His [website](https://xcelab.net/rm/) is also a great source for talks and posts.

#### [The effect](https://theeffectbook.net/index.html) (2022)

The effect is a gentle introduction to causal inference, written by Nick Huntington-Klein. The first part is an introduction to all the intuition that supports causal inference. The second part is an explanation of different statistical models for causal inference. The language used is accessible and there is not too much math, so the reading is easier than other books. 

#### Statistical Inference as Severe Testing (2018)

#### [Modern Statistics with R](https://www.modernstatisticswithr.com/) (2021)

This is a book that covers many aspects of applying statistics in R. There are some chapters with basic material (if you are experienced with R, you are safe to skip them). After chapter 7, there is a wide range of topics on statistics, one of my favorites are the chapters talking about ethics issues with statistical inferences. This is a very applied book, with a lot of code examples in R.

#### [Statistical Inference via Data Science](https://moderndive.com/) (2022)

Another hands-on book, with a lot a code in R to apply sampling techniques for statistical inferences. What I really like about this book is that it uses a very didactic approach, and it also applies modern packages (infer, from [tidymodels](https://www.tidymodels.org/)) to perform the statistical inferences.

# Programming

#### [R for Data Science](https://r4ds.had.co.nz/)

This is the book that finally made me start thriving in programming and data analyses. It was written by Hadley Wickham (a big reference in the R community). The book is an introduction to the use of a collection of packages, called the [tidyverse](https://www.tidyverse.org/)

#### [Happy Git and GitHub for the useR](https://happygitwithr.com/)

This is an essential book to learn version control with R! It is written by another reference to the R community, Jennifer Bryan. It teaches you how to start integrating your R projects with git and github, such an important resource if you want to produce high quality projects.

#### [Advanced R](https://adv-r.hadley.nz/)

Another book by Hadley Wickham, but differently from [R for Data Science](https://r4ds.had.co.nz/), it teaches specific skills with R that helps specially with the package development. My favorite section is the Functional Programming.

#### [Mastering Spark with R](https://therinspark.com/)

Spark helped me a lot when I needed to analyse a data set that could not fit in my computer memory. Even though I just used I tiny part of the whole capability of Spark, it was a great solution for my problem. I expect working more with Spark, and start using connections and applying machine learning algorithms with Spark. 

# Data Communication

#### [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) (2020)

####  [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/) (2016)

#### [Chartability](https://chartability.fizz.studio/)

The author of chartability is [Frank Elavsky](https://www.frank.computer), which is a reference for me concerning accessibility. He developed the chartability which is a framework to evaluate and develop more accessible data visualizations. There is also a document explaining the creation and usage of chartability: [How accessible is my visualization? Evaluating visualization accessibility with Chartability](https://www.frank.computer/chartability/#) (2022).

#### [Hands-On Data Visualization](https://handsondataviz.org/) (2022)

#### [Telling Stories with Data](https://tellingstorieswithdata.com/) (2023)

#### Report Writing for Data Science in R (2019)

# Modelling

#### Modelling Mindsets (2022)

This is an amazing overview of different modeling approaches. Written by Christoph Molnar, in a very fluid and pedagogical manner. I strongly recommend reading this book if you are into modeling, and already have familiarity with statistics.

#### [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/) (2022)

This is another exceptional book, also written by Christoph Molnar. This book aims to present ways to interpret models. Some chapters deal with models that are naturally easier to interpret. Other chapters deal with methodologies that can be applied to any model, even those that are more difficult to interpret. A must read for anyone working with modeling.

#### The Art of Data Science (2018)

#### [Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/) (2021)

#### [Tidy Modelling with R](https://www.tmwr.org/) (2022)

#### [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/) (2020)

#### [Explanatory Model Analysis](https://ema.drwhy.ai/) (2020)

#### [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering/) (2019)

#### [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/) (2022)

#### [MLU-Explain](https://mlu-explain.github.io/)

# Spatial analysis

#### [Geocomputation with R](https://geocompr.robinlovelace.net/) (2023)

#### [Satellite Image Time Series Analysis on Earth Observation Data Cubes](https://e-sensing.github.io/sitsbook/) (2022)

#### [Spatial Data Science](https://r-spatial.org/book/) (2022)

This is a book written by Edzer Pebesma. He is a reference for me, concerning spatial data manipulation. I have learned so much from him, he has made a great work developing R packages for spatial analytics, and really helped the development of this area in the R community. This is an amazing book with essential information for anyone interested on spatial data analysis, and even though it is focused on the R language, it can provide precious information to users of any type!

# Project Management

#### Project Management Fundamentals for Data Analysts (2021)

:::

::: {.content-visible when-profile="pt"}

Esta é uma lista de recursos da qual estou sempre buscando informações, considero como materiais essenciais para meu trabalho profissional como pesquisador e analista de dados. Se você não puder ter acesso a nenhum deles, por favor, entre em contato comigo por e-mail para que eu possa tentar ajudá-lo.

# Estatística

#### Statistical Rethinking (2019)

Este livro é escrito por Richard McElreath, fala sobre uma maneira diferente de interpretar a estatística e suas inferências.
Seu [site](https://xcelab.net/rm/) também é uma ótima fonte para palestras e posts.

#### [The effect](https://theeffectbook.net/index.html) (2022)

O efeito é uma suave introdução à inferência causal, escrita por Nick Huntington-Klein. A primeira parte é uma introdução a toda a intuição que da base à inferência causal. A segunda parte é uma explicação de diferentes modelos estatísticos para a inferência causal. A linguagem utilizada é acessível e não há muita matemática, portanto, a leitura é mais fácil do que outros livros. 

#### Statistical Inference as Severe Testing (2018)

#### [Modern Statistics with R](https://www.modernstatisticswithr.com/) (2021)

Este é um livro que cobre muitos aspectos da aplicação de estatísticas em R. Há alguns capítulos com material básico (se você tem experiência com R, você  pode ignorá-los). Após o capítulo 7, há uma grande variedade de tópicos sobre estatística, um dos meus favoritos são os capítulos que falam sobre questões éticas com inferências estatísticas. Este é um livro muito aplicado, com muitos exemplos de código em R.

#### [Statistical Inference via Data Science](https://moderndive.com/) (2022)

Outro livro prático, com muito código em R para aplicar técnicas de amostragem para inferências estatísticas. O que eu realmente gosto neste livro é que ele usa uma abordagem muito didática, e também aplica pacotes modernos (infer, de [tidymodels](https://www.tidymodels.org/)) para realizar as inferências estatísticas.

# Programação

#### [R for Data Science](https://r4ds.had.co.nz/)

Este é o livro que me fez começar a prosperar em programação e análise de dados. Ele foi escrito por Hadley Wickham (uma grande referência na comunidade R). O livro é uma introdução ao uso de uma coleção de pacotes, chamada [tidyverse](https://www.tidyverse.org/).

#### [Happy Git and GitHub for the useR](https://happygitwithr.com/)

Este é um livro essencial para aprender controle de versão com R! É escrito por outra referência na comunidade R, Jennifer Bryan. Ela ensina como começar a integrar seus projetos de R com git e github, um recurso tão importante se você quiser produzir projetos de alta qualidade.

#### [Advanced R](https://adv-r.hadley.nz/)

Outro livro de Hadley Wickham, mas diferente do [R for Data Science](https://r4ds.had.co.nz/), ensina habilidades específicas com R que ajuda especialmente no desenvolvimento de pacotes. Minha seção favorita é a Programação Funcional.

#### [Mastering Spark with R](https://therinspark.com/)

O Spark me ajudou muito quando eu precisava analisar um conjunto de dados grande, que não cabia na memória do meu computador. Embora eu tenha usado apenas uma pequena parte de toda a capacidade da Spark, foi uma grande solução para o meu problema. Espero trabalhar mais com essa ferramenta, e começar a usar conexões e aplicar algoritmos de aprendizagem da máquina com a Spark. 

# Visualização e comunicação de dados

#### [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) (2020)

####  [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/) (2016)

#### [Chartability](https://chartability.fizz.studio/)

O autor de Chartability é [Frank Elavsky](https://www.frank.computer), que é para mim uma referência na questão de acessibilidade na visualização de dados. Ele desenvolveu a Chartability que é uma metodologia para avaliar e desenvolver visualizações de dados mais acessíveis. Há também um documento que explica a criação e o uso da Chartability: [How accessible is my visualization? Evaluating visualization accessibility with Chartability](https://www.frank.computer/chartability/#) (2022).

#### [Hands-On Data Visualization](https://handsondataviz.org/) (2022)

#### [Telling Stories with Data](https://tellingstorieswithdata.com/) (2023)

#### Report Writing for Data Science in R (2019)

# Modelagem

#### Modelling Mindsets (2022)

Este é um excelente panorama de diferentes abordagens de modelagem. Escrito por Christoph Molnar, de uma maneira muito fluida e pedagógica. Recomendo muito a leitura deste livro se você gosta de modelagem, e já tem familiaridade com estatística.

#### [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/) (2022)

Esse é outro livro excepcional, também escrito por Christoph Molnar. Esse livro tem como objetivo apresentar formas de interpretar modelos. Alguns capítulos abordam modelos que são naturalmente mais fáceis de interpretar. Outros capitulos tratam de metodologias que podem ser aplicadas em qualquer modelo, até naqueles que são mais difíceis de serem interpretados. Uma leitura que recomendo para qualquer pessoa que trabalhe com modelagem.

#### The Art of Data Science (2018)

#### [Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/) (2021)

#### [Tidy Modelling with R](https://www.tmwr.org/) (2022)

#### [Hands-On Machine Learning with R](https://bradleyboehmke.github.io/HOML/) (2020)

#### [Explanatory Model Analysis](https://ema.drwhy.ai/) (2020)

#### [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering/) (2019)

#### [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/) (2022)

#### [MLU-Explain](https://mlu-explain.github.io/)

# Análise espacial

#### [Geocomputation with R](https://geocompr.robinlovelace.net/) (2023)

#### [Satellite Image Time Series Analysis on Earth Observation Data Cubes](https://e-sensing.github.io/sitsbook/) (2022)

#### [Spatial Data Science](https://r-spatial.org/book/) (2022)

Este é um livro escrito por Edzer Pebesma. Ele é uma referência para mim, no que diz respeito à manipulação de dados espaciais. Aprendi tanto com ele pelo seu trabalho desenvolvendo pacotes de R para análise espacial. Este é um livro excelente, com informações essenciais para qualquer pessoa interessada na análise de dados espaciais, e mesmo que  seja focado na linguagem R, ele pode fornecer informações preciosas para usuários de qualquer tipo!

Traduzido com a versão gratuita do tradutor - www.DeepL.com/Translator

# Gestão de projetos

#### Project Management Fundamentals for Data Analysts (2021)

:::